# Generated by Django 2.2.12 on 2024-04-21 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idclient', models.IntegerField()),
                ('nomclient', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('methoddepot', models.CharField(default=0, max_length=50)),
                ('nomdepot', models.CharField(default=0, max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('idtransfert', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de transfert')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.IntegerField(default=0)),
                ('parain', models.IntegerField(default=0)),
                ('phone', models.CharField(default=0, max_length=10)),
                ('idparain', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
